<?php

namespace CS\PlatformHandlingBundle\Repository;

/**
 * AdministrativeServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativeServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdminServiceWithRoles($id)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.roles', 'ad')->addSelect('ad');
        

        $qb->where('a.id = :id');
        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAllAdminServices()
    {
            $qb = $this->createQueryBuilder('a');
            $qb->orderBy('a.name', 'asc');
            $qb->addOrderBy('a.code', 'asc');
            $qb->addOrderBy('a.price', 'asc');            

            return $qb->getQuery()->getResult();
    }
}
