<?php

namespace CS\PlatformHandlingBundle\Repository;

/**
 * RolesOfCoolSchoolEmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesOfCoolSchoolEmployeesRepository extends \Doctrine\ORM\EntityRepository
{
}
