<?php

namespace CS\CustomersPlatformBundle\Repository;

/**
 * CustomerUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerUserRepository extends \Doctrine\ORM\EntityRepository
{
    
}
