<?php

namespace CS\CustomersPlatformBundle\Repository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    /* recupère l'école avec le logo et le pays */
    public function getSchoolProperties($id)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.country' , 'c')->addSelect('c');
        $qb->leftJoin('s.logo' , 'i')->addSelect('i');
       
        $qb->where('s.id = :id');

        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getSchoolPropertiesWithSubscriptions($id)
    {
        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.country' , 'c')->addSelect('c');
        $qb->leftJoin('s.logo' , 'i')->addSelect('i');
        $qb->leftJoin('s.subscriptions' , 'su')->addSelect('su');
       
        $qb->where('s.id = :id');

        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
