<?php

namespace CS\CustomersPlatformBundle\Repository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends \Doctrine\ORM\EntityRepository
{
    /* on récupère un ou les rôles joué(s) dans une école par ses utilisateurs*/
    public function getWorksBySchoolAndRole($schoolId, $roleCode)
    {
        $qb = $this->createQueryBuilder('w');

        $qb->leftJoin('w.school' , 's')->addSelect('s');
        $qb->leftJoin('w.role' , 'c')->addSelect('c');
        $qb->leftJoin('w.customerUser' , 'cu')->addSelect('cu');
        
       
        $qb->where('s.id = :id');
        $qb->andWhere('c.code = :code');

        $qb->setParameters(array('id'=>$schoolId, 'code'=>$roleCode));

        return $qb->getQuery()->getResult();
    }
}
