services:
#    cs_core.example:
#        class: CS\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    cs_core.authentication.event.listener:
        class: CS\CoreBundle\Services\AuthenticationEventListener
        arguments: ["@router", "@doctrine", "@event_dispatcher"]
        tags: 
          - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }




    cs_core.requestStack:
        class: CS\CoreBundle\Services\MyRequestStack
        arguments: ["@request_stack"]
      